version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
        
    steps:
      - checkout
      # Instalacja narzędzia make na maszynie w chmurze:
      - run: sudo apt-get update && sudo apt-get install -y make
      - run: make deps
      - run: make test       

workflows:
  basic:
    jobs:
      - build-and-test