version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
        
    steps:
      - checkout
      - run:
          name: Instalacja make oraz przygotowanie srodowiska Python
          command: |
            sudo apt-get update && sudo apt-get install -y make
            python3 -m venv .venv
            source .venv/bin/activate
            make deps

      - run:
          name: Uruchomienie testów jednostkowych
          command: |
            source .venv/bin/activate
            make test

workflows:
  basic:
    jobs:
      - build-and-test